### ISSUE TITLE
Can't import using swift package manager

### ISSUE THREAD

**Issue by orelzion** [geekaurora/SwiftWebImage#2]
I'm trying to import this library, but this is what I get
```
The package dependency graph can not be resolved, possibly because of these requirements:

https://github.com/geekaurora/SwiftWebImage.git — 3.3.2
```

<img width="726" alt="Screen Shot 2020-05-26 at 16 48 15" src="https://user-images.githubusercontent.com/1846941/82908501-bc264680-9f70-11ea-849b-3788f257910b.png">

**Comment by geekaurora** [comment]
Hey orelzion,

Thanks for the great feedback! 

Tested in [example project](https://github.com/geekaurora/SwiftWebImage/tree/master/Example), replaced local package with `https://github.com/geekaurora/SwiftWebImage.git` -- it worked.
Xcode version: 11.4

Couldn't get concrete clue based on the screenshot, will test further in this weekend.
Meanwhile, you can drag SwiftWebImage folder to your project as a workaround.

Best,
Tony

**Comment by orelzion** [comment]
Thank you so much! I'll try that

**Comment by geekaurora** [comment]
Tested more still couldn't repo the issue. Possibly was related with Xcode compatibility. please ensure integrate with Xcode11.4. Will revisit when get more time :)
